export const data = [
  {
    user_id: 1,
    first_name: "Augustin",
    last_name: "Towndrow",
    age: 46,
    gender: "Male",
    email: "atowndrow0@walmart.com",
    country: "China",
    job_title: "Nuclear Power Engineer",
    favorite_color: "green",
    language: "Latvian",
  },
  {
    user_id: 2,
    first_name: "Dorree",
    last_name: "Spens",
    age: 28,
    gender: "Female",
    email: "dspens1@livejournal.com",
    country: "Brazil",
    job_title: "Pharmacist",
    favorite_color: "blue",
    language: "German",
  },
  {
    user_id: 3,
    first_name: "Stanleigh",
    last_name: "Willans",
    age: 51,
    gender: "Male",
    email: "swillans2@yahoo.com",
    country: "Canada",
    job_title: "Computer Systems Analyst I",
    favorite_color: "blue",
    language: "Filipino",
  },
  {
    user_id: 4,
    first_name: "Kathlin",
    last_name: "Danihel",
    age: 27,
    gender: "Female",
    email: "kdanihel3@sphinn.com",
    country: "Portugal",
    job_title: "Administrative Officer",
    favorite_color: "red",
    language: "Pashto",
  },
  {
    user_id: 5,
    first_name: "Keelby",
    last_name: "Opdenort",
    age: 37,
    gender: "Male",
    email: "kopdenort4@state.tx.us",
    country: "Indonesia",
    job_title: "Cost Accountant",
    favorite_color: "red",
    language: "Korean",
  },
  {
    user_id: 6,
    first_name: "Donny",
    last_name: "Sterland",
    age: 38,
    gender: "Female",
    email: "dsterland5@reference.com",
    country: "United States",
    job_title: "Environmental Specialist",
    favorite_color: "green",
    language: "Dari",
  },
  {
    user_id: 7,
    first_name: "Alida",
    last_name: "Ginsie",
    age: 63,
    gender: "Female",
    email: "aginsie6@apache.org",
    country: "Sweden",
    job_title: "Geologist II",
    favorite_color: "red",
    language: "Maltese",
  },
  {
    user_id: 8,
    first_name: "Meridel",
    last_name: "Maillard",
    age: 21,
    gender: "Female",
    email: "mmaillard7@narod.ru",
    country: "China",
    job_title: "Geologist I",
    favorite_color: "blue",
    language: "Japanese",
  },
  {
    user_id: 9,
    first_name: "Lesya",
    last_name: "Rosenfarb",
    age: 75,
    gender: "Female",
    email: "lrosenfarb8@omniture.com",
    country: "Indonesia",
    job_title: "Registered Nurse",
    favorite_color: "blue",
    language: "Montenegrin",
  },
  {
    user_id: 10,
    first_name: "Bank",
    last_name: "Gorcke",
    age: 70,
    gender: "Male",
    email: "bgorcke9@utexas.edu",
    country: "Canada",
    job_title: "Web Designer I",
    favorite_color: "green",
    language: "Punjabi",
  },
  {
    user_id: 11,
    first_name: "Shaylynn",
    last_name: "Phippen",
    age: 18,
    gender: "Bigender",
    email: "sphippena@acquirethisname.com",
    country: "Zimbabwe",
    job_title: "Budget/Accounting Analyst III",
    favorite_color: "green",
    language: "Papiamento",
  },
  {
    user_id: 12,
    first_name: "Lin",
    last_name: "Bowart",
    age: 69,
    gender: "Male",
    email: "lbowartb@1und1.de",
    country: "Indonesia",
    job_title: "Marketing Manager",
    favorite_color: "red",
    language: "Latvian",
  },
  {
    user_id: 13,
    first_name: "Adriena",
    last_name: "Vaneev",
    age: 56,
    gender: "Non-binary",
    email: "avaneevc@baidu.com",
    country: "Greece",
    job_title: "Accounting Assistant IV",
    favorite_color: "red",
    language: "Punjabi",
  },
  {
    user_id: 14,
    first_name: "Gaspard",
    last_name: "Mainson",
    age: 62,
    gender: "Male",
    email: "gmainsond@independent.co.uk",
    country: "Venezuela",
    job_title: "Senior Sales Associate",
    favorite_color: "green",
    language: "Italian",
  },
  {
    user_id: 15,
    first_name: "Walsh",
    last_name: "Hyndes",
    age: 71,
    gender: "Male",
    email: "whyndese@webnode.com",
    country: "France",
    job_title: "Statistician IV",
    favorite_color: "red",
    language: "Luxembourgish",
  },
  {
    user_id: 16,
    first_name: "Gaby",
    last_name: "Josilevich",
    age: 39,
    gender: "Male",
    email: "gjosilevichf@google.com.br",
    country: "Bulgaria",
    job_title: "Electrical Engineer",
    favorite_color: "blue",
    language: "Dhivehi",
  },
  {
    user_id: 17,
    first_name: "Gabby",
    last_name: "Cape",
    age: 38,
    gender: "Male",
    email: "gcapeg@opera.com",
    country: "Indonesia",
    job_title: "Assistant Manager",
    favorite_color: "green",
    language: "Irish Gaelic",
  },
  {
    user_id: 18,
    first_name: "Boycie",
    last_name: "Brogiotti",
    age: 78,
    gender: "Male",
    email: "bbrogiottih@wikispaces.com",
    country: "China",
    job_title: "Research Assistant II",
    favorite_color: "red",
    language: "Māori",
  },
  {
    user_id: 19,
    first_name: "Tabby",
    last_name: "Sandaver",
    age: 35,
    gender: "Male",
    email: "tsandaveri@g.co",
    country: "Ukraine",
    job_title: "Financial Advisor",
    favorite_color: "red",
    language: "Thai",
  },
  {
    user_id: 20,
    first_name: "Brittan",
    last_name: "Boxhall",
    age: 80,
    gender: "Female",
    email: "bboxhallj@biblegateway.com",
    country: "Canada",
    job_title: "Administrative Officer",
    favorite_color: "blue",
    language: "Bengali",
  },
  {
    user_id: 21,
    first_name: "Nessie",
    last_name: "Humphrey",
    age: 47,
    gender: "Female",
    email: "nhumphreyk@ezinearticles.com",
    country: "Portugal",
    job_title: "Structural Analysis Engineer",
    favorite_color: "red",
    language: "Bislama",
  },
  {
    user_id: 22,
    first_name: "Scott",
    last_name: "Roland",
    age: 61,
    gender: "Genderfluid",
    email: "srolandl@businesswire.com",
    country: "Malaysia",
    job_title: "Engineer I",
    favorite_color: "blue",
    language: "English",
  },
  {
    user_id: 23,
    first_name: "Vonny",
    last_name: "Hardan",
    age: 77,
    gender: "Female",
    email: "vhardanm@theatlantic.com",
    country: "Japan",
    job_title: "Safety Technician III",
    favorite_color: "green",
    language: "English",
  },
  {
    user_id: 24,
    first_name: "Sandy",
    last_name: "Cookman",
    age: 51,
    gender: "Female",
    email: "scookmann@mapy.cz",
    country: "Sweden",
    job_title: "Mechanical Systems Engineer",
    favorite_color: "blue",
    language: "Amharic",
  },
  {
    user_id: 25,
    first_name: "Dunc",
    last_name: "Hurst",
    age: 42,
    gender: "Male",
    email: "dhursto@msn.com",
    country: "Azerbaijan",
    job_title: "Registered Nurse",
    favorite_color: "red",
    language: "Tajik",
  },
  {
    user_id: 26,
    first_name: "Clair",
    last_name: "Allans",
    age: 84,
    gender: "Male",
    email: "callansp@flavors.me",
    country: "Vietnam",
    job_title: "Civil Engineer",
    favorite_color: "red",
    language: "Swati",
  },
  {
    user_id: 27,
    first_name: "Welby",
    last_name: "Torre",
    age: 25,
    gender: "Male",
    email: "wtorreq@acquirethisname.com",
    country: "Russia",
    job_title: "Human Resources Manager",
    favorite_color: "red",
    language: "Sotho",
  },
  {
    user_id: 28,
    first_name: "Maison",
    last_name: "Searsby",
    age: 82,
    gender: "Male",
    email: "msearsbyr@auda.org.au",
    country: "Poland",
    job_title: "Design Engineer",
    favorite_color: "green",
    language: "Afrikaans",
  },
  {
    user_id: 29,
    first_name: "Ross",
    last_name: "Venner",
    age: 48,
    gender: "Male",
    email: "rvenners@devhub.com",
    country: "China",
    job_title: "Research Nurse",
    favorite_color: "blue",
    language: "Pashto",
  },
  {
    user_id: 30,
    first_name: "Reina",
    last_name: "Shrubshall",
    age: 26,
    gender: "Female",
    email: "rshrubshallt@illinois.edu",
    country: "Belarus",
    job_title: "Account Executive",
    favorite_color: "blue",
    language: "Tok Pisin",
  },
];
